#!/bin/sh
# Part 3 greeting
# Jajuan Burton 31 MAY 2017
#
#
#
PATH=/Users/burton/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/bin

LOOP=0
MAXLOOP=5
TODAY=`date +%H`

while [ $LOOP -le $MAXLOOP ]
do
	echo "What is your name? \c"
	read  NAME
	TRNAME=`echo $NAME | tr -d [:cntrl:] | tr -d [:special:] | tr -d [:punct:] | tr -d [:digit:]`
	LENGTH=`echo ${#NAME}`
	if [ $LENGTH -gt 25 ] 
	then
		echo "Invalid input. What is your name?"
	elif [ x$NAME = x ]
	then
		echo "No valid input. What is your name?"
	elif [ "$NAME" = "$TRNAME" ] 
	then
		break
	else
		echo "Invalid input. What is your name?"
	
	fi
	LOOP=`expr $LOOP + 1`
        if [ $LOOP -gt $MAXLOOP ]
        then
        	echo "Too Many tries BIG FELLA!"
        	exit 1
        fi
done


while [ $TODAY -ge 00 -a $TODAY -le 11 ]
do
	echo "Good Morning, $NAME."
	break
done
while [ $TODAY -ge 12 -a $TODAY -le 17 ]
do
	echo "Good Afternoon, $NAME."
	break
done
while [ $TODAY -ge 18 -a $TODAY -le 20 ]
do
	echo "Good Evening, $NAME."
	break
done
while [ $TODAY -ge 21 -a $TODAY -le 23 ]
do
	echo "Good Night, $NAME."
done
