#!/bin/sh 
# Jay Price
# - greeting: This page prints the greeting appropriate for the time of day.
#
#

CURR_HOUR=`date +%H`

echo "What is your name?\c"
read NAME

if [ $CURR_HOUR -ge 0 -a $CURR_HOUR -lt 12 ]
then
	echo "$NAME, Good Morning."
elif [ $CURR_HOUR -ge 12 -a $CURR_HOUR -lt 18 ]
then
	echo "$NAME, Good Afternoon."
elif [ $CURR_HOUR -ge 18 -a $CURR_HOUR -lt 24]
then
	echo "$NAME, Good Evening."
fi
